# Generated by Django 4.1.7 on 2023-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerTrainingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.IntegerField(default=0),
        ),
    ]
